---
title: "NeuronConnect_R"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library("igraph")
library("plyr")
```



#Preparacio dades C.Elegans


```{r}
# documentacio matriu https://www.wormatlas.org/neuronalwiring.html#NeuronalconnectivityII
# documentacio igraph https://kateto.net/netscix2016.html

archiu <- read.csv("NeuronConnect.csv",sep = ";")

unique(archiu$Type)


ab <- nrow(archiu)
for (i in 1:ab) {
  if(archiu[i,3]=="R" | archiu[i,3]=="Rp"){
    archiu[i,] <- archiu[i, c(2,1,3,4)]
  }
  if(archiu[i,3]=="EJ"){
  
    archiu <- rbind.fill(archiu,archiu[i,])
  }
}

g <- graph_from_edgelist(as.matrix(archiu[,c(1,2)]), directed = TRUE)

E(g)$weight <- archiu$Nbr
E(g)$name <- archiu$Type


gs <- simplify( g , remove.multiple = T, remove.loops = F, edge.attr.comb=c(weight="sum", type="ignore") )
```

```{r}
l <- layout_with_fr(gs)
plot(gs, rescale=F, layout=l*0.4)
```

```{r}
l <- layout_with_fr(gs)

V(gs)$color <- colrs[V(gs)$media.type]

V(gs)$size <- V(gs)$audience.size*0.7

V(gs)$label.color <- "black"

V(gs)$label <- NA

E(gs)$width <- E(gs)$weight/6

E(gs)$arrow.size <- .2

E(gs)$width <- 1+E(gs)$weight/12

plot(gs,rescale=F,layout=l*0.8)
```

```{r}
barplot(triad_census(gs), log="y")
```

```{r}
#Color nodes along the diameter:

diam <- get_diameter(gs, directed=T)

as.vector(diam)

vcol <- rep("gray40", vcount(gs))

vcol[diam] <- "gold"

ecol <- rep("gray80", ecount(gs))

ecol[E(gs, path=diam)] <- "orange" 


plot(gs, rescale=F,vertex.color=vcol, edge.color=ecol, edge.arrow.mode=0)
```

```{r}
#encontrar el camino más corto entre nodos específicos.

news.path <- shortest_paths(gs, 

                            from = V(gs)[as.list(names)=="ADFL"], 

                             to  = V(gs)[as.list(names)=="SMBVR"],

                             output = "both") # both path nodes and edges



# Generate edge color variable to plot the path:

ecol <- rep("gray80", ecount(gs))

ecol[unlist(news.path$epath)] <- "orange"

# Generate edge width variable to plot the path:

ew <- rep(2, ecount(gs))

ew[unlist(news.path$epath)] <- 4

# Generate node color variable to plot the path:

vcol <- rep("gray40", vcount(gs))

vcol[unlist(news.path$vpath)] <- "gold"



plot(gs,rescale=F, vertex.color=vcol, edge.color=ecol, 

     edge.width=ew, edge.arrow.mode=0)
```

```{r}
inc.edges <- incident(gs,  V(gs)[media=="ADFL"], mode="all")



# Set colors to plot the selected edges.

ecol <- rep("gray80", ecount(gs))

ecol[inc.edges] <- "orange"

vcol <- rep("grey40", vcount(gs))

vcol[V(gs)$media=="ADFL"] <- "gold"

plot(gs,rescale=F, vertex.color=vcol, edge.color=ecol)
```

```{r}
cocitation(gs)
```

```{r}
#comunidades
ceb <- cluster_edge_betweenness(gs) 

plot(ceb, gs) 
```

```{r}
cfg <- cluster_fast_greedy(as.undirected(gs))

plot(cfg, as.undirected(gs))

l <- layout_with_fr(gs)

plot(cfg, resacle=F, as.undirected(gs), layout=l*1.0)

```




##-------------------------------------------------------------------------------------------------------------------
```{r}
#Degree distribution


plot(gs, vertex.size=6, vertex.label=NA, layout=layout_in_circle)  


deg <- degree(gs, mode="all")

deg.distF <- degree_distribution(gs, cumulative=F, mode="all")

deg.distT <- degree_distribution(gs, cumulative=T, mode="all")



#Triad census
tirad_gs = triad_census(gs)

#Hubs
hs_gs <- hub_score(gs, weights=NA)$vector

#Authorities
as_gs <- authority_score(gs, weights=NA)$vector


#Small-Worldness ratio: 
SM_Ratio_gs = transitivity(gs)/mean_distance(gs)

#modularity
library(leiden)
adj_mtx_gs  <- igraph::as_adjacency_matrix(gs)
wtc_gs <- leiden(adj_mtx_gs)
modularity_gs <- modularity(gs, wtc_gs)

#comunitats
comunitats_gs <- cluster_louvain(gs)
communitySize_gs <- comunitats_gs

#cliques
cliques_gs <- cliques(gs)

#n nodes
nNodes_gs <- gsize(gs)

#routing efficiency
am_gs  <- get.adjacency(gs)
distances_gs <- distances(gs , mode = "in", weights=1/E(gs)$weight)

library(gmp)
rout_effs_gs <- as.numeric(as.bigz(1/distances_gs)/as.bigz(dim(am_gs)[[1]]*(dim(am_gs)[[1]]-1)))
rout_effs_matrix_gs <- as.matrix(rout_effs_gs)
rout_effs_matrix_gs <- rout_effs_matrix_gs[is.finite(rout_effs_matrix_gs)]
rout_eff_gs <- as.numeric(sum(rout_effs_matrix_gs))

#storage capacity
storage_caps_gs <- numeric()
library(Matrix)
for(j in 1:dim(am_gs)[[1]]){
  storage_caps_gs <- append(storage_caps_gs, as.integer(2*log2(chooseZ(as.bigz(sum(am_gs[,j]) + nnzero(am_gs[,j]) -1), as.bigz(sum(am_gs[,j]))))))
}
storage_cap_gs <- mean(storage_caps_gs)#,na.rm=T)

celegans_data <- list()
celegans_data[["deg_distF_celegans"]] <- deg.distF
celegans_data[["deg_distT_celegans"]] <- deg.distT
celegans_data[["triad_census_celegans"]] <- tirad_gs
celegans_data[["hub_score_celegans"]] <- hs_gs
celegans_data[["modularity_celegans"]] <- modularity_gs
celegans_data[["authority_score_celegans"]] <- as_gs 
celegans_data[["communitySize_celegans"]] <- communitySize_gs
celegans_data[["SW_ratio_celegans"]] <- SM_Ratio_gs 
celegans_data[["cliques_celegans"]] <- cliques_gs 
celegans_data[["nNodes_celegans"]] <- nNodes_gs 
celegans_data[["rout_eff_celegans"]] <- rout_eff_gs 
celegans_data[["storage_cap_celegans"]] <- storage_cap_gs




save(celegans_data, file="celegans_data.RData")

load("celegans_data.RData")

```


# ---GENERAR 3 XARXES ALEATORIES PER COMPARAR---

## Erdos-Renyi random graph model

```{r}
set.seed(2706)

er_xarxa1 <- sample_gnm(n=283, m=3109, directed = TRUE) 

deg_xarxa1 <- degree(er_xarxa1, mode="all")

deg.dist_xarxaF1 <- degree_distribution(er_xarxa1, cumulative=F, mode="all")

deg.dist_xarxaT1 <- degree_distribution(er_xarxa1, cumulative=T, mode="all")


tirad_er_xarxa1 = triad_census(er_xarxa1)


#Hubs
hs_er_xarxa1 <- hub_score(er_xarxa1, weights=NA)$vector


#Authorities
as_er_xarxa1 <- authority_score(er_xarxa1, weights=NA)$vector


#Small-Worldness ratio: 
SM_Ratio_er_xarxa1 = transitivity(er_xarxa1)/mean_distance(er_xarxa1)


#modularity
library(leiden)
adj_mtx_er_xarxa1  <- igraph::as_adjacency_matrix(er_xarxa1)
wtc_er_xarxa1 <- leiden(adj_mtx_er_xarxa1)
modularity_er_xarxa1 <- modularity(er_xarxa1, wtc_er_xarxa1)

#comunitats
comunitats_er_xarxa1 <- cluster_louvain(er_xarxa1)
communitySize_er_xarxa1 <- comunitats_er_xarxa1

#cliques
cliques_er_xarxa1 <- cliques(er_xarxa1)

#n nodes
nNodes_er_xarxa1 <- gsize(er_xarxa1)

#routing efficiency
am_xarxa1  <- get.adjacency(er_xarxa1)
distances_xarxa1 <- distances(er_xarxa1 , mode = "in", weights=1/E(am_xarxa1)$weight)

library(gmp)
rout_effs_xarxa1 <- as.numeric(as.bigz(1/distances_xarxa1)/as.bigz(dim(am_xarxa1)[[1]]*(dim(am_xarxa1)[[1]]-1)))
rout_effs_matrix_xarxa1 <- as.matrix(rout_effs_xarxa1)
rout_effs_matrix_xarxa1 <- rout_effs_matrix_xarxa1[is.finite(rout_effs_matrix_xarxa1)]
rout_eff_xarxa1 <- as.numeric(sum(rout_effs_matrix_xarxa1))

#storage capacity
storage_caps_xarxa1 <- numeric()
library(Matrix)
for(j in 1:dim(am_xarxa1)[[1]]){
  storage_caps_xarxa1 <- append(storage_caps_xarxa1, as.integer(2*log2(chooseZ(as.bigz(sum(am_xarxa1[,j]) + nnzero(am_xarxa1[,j]) -1), as.bigz(sum(am_xarxa1[,j]))))))
}
storage_cap_xarxa1 <- mean(storage_caps_xarxa1)#,na.rm=T)

celegansER_data <- list()
celegansER_data[["deg_distF_celegansER"]] <- deg.dist_xarxaF1
celegansER_data[["deg_distT_celegansER"]] <- deg.dist_xarxaT1
celegansER_data[["triad_census_celegansER"]] <- tirad_er_xarxa1
celegansER_data[["hub_score_celegansER"]] <- hs_er_xarxa1
celegansER_data[["modularity_celegansER"]] <- modularity_er_xarxa1
celegansER_data[["authority_score_celegansER"]] <- as_er_xarxa1
celegansER_data[["communitySize_celegansER"]] <- communitySize_er_xarxa1
celegansER_data[["SW_ratio_celegansER"]] <- SM_Ratio_er_xarxa1 
celegansER_data[["cliques_celegansER"]] <- cliques_er_xarxa1 
celegansER_data[["nNodes_celegansER"]] <- nNodes_er_xarxa1 
celegansER_data[["rout_eff_celegansER"]] <- rout_eff_xarxa1
celegansER_data[["storage_celegansER"]] <- storage_cap_xarxa1


save(celegansER_data, file="celegansER_data.RData")

load("celegansER_data.RData")


```





## Watts-Strogatz small-world model

```{r}
sw_xarxa2 <- sample_smallworld(dim=1, size=283, nei=11, p=0.1)
plot(sw_xarxa2, vertex.size=6, vertex.label=NA, layout=layout_in_circle)


deg_xarxa2 <- degree(sw_xarxa2, mode="all")


deg.dist_xarxaF2 <- degree_distribution(sw_xarxa2, cumulative=F, mode="all")

deg.dist_xarxaT2 <- degree_distribution(sw_xarxa2, cumulative=T, mode="all")


tirad_sw_xarxa2 = triad_census(sw_xarxa2)

#Hubs
hs_sw_xarxa2 <- hub_score(sw_xarxa2, weights=NA)$vector

#Authorities
as_sw_xarxa2 <- authority_score(sw_xarxa2, weights=NA)$vector

#Small-Worldness ratio: 
SM_Ratio_sw_xarxa2 = transitivity(sw_xarxa2)/mean_distance(sw_xarxa2)

#modularity
library(leiden)
adj_mtx_sw_xarxa2  <- igraph::as_adjacency_matrix(sw_xarxa2)
wtc_sw_xarxa2 <- leiden(adj_mtx_sw_xarxa2)
modularity_sw_xarxa2 <- modularity(sw_xarxa2, wtc_sw_xarxa2)

#comunitats
comunitats_sw_xarxa2 <- cluster_louvain(sw_xarxa2)
communitySize_sw_xarxa2 <- comunitats_sw_xarxa2

#cliques
cliques_sw_xarxa2 <- cliques(sw_xarxa2)

#n nodes
nNodes_sw_xarxa2 <- gsize(sw_xarxa2)

#routing efficiency
am_sw_xarxa2 <- get.adjacency(sw_xarxa2)
distances_sw_xarxa2 <- distances(sw_xarxa2 , mode = "in", weights=1/E(am_sw_xarxa2)$weight)

library(gmp)
rout_effs_sw_xarxa2 <- as.numeric(as.bigz(1/distances_sw_xarxa2)/as.bigz(dim(am_sw_xarxa2)[[1]]*(dim(am_sw_xarxa2)[[1]]-1)))
rout_effs_matrix_sw_xarxa2 <- as.matrix(rout_effs_sw_xarxa2)
rout_effs_matrix_sw_xarxa2 <- rout_effs_matrix_sw_xarxa2[is.finite(rout_effs_matrix_sw_xarxa2)]
rout_eff_sw_xarxa2 <- as.numeric(sum(rout_effs_matrix_sw_xarxa2))

#storage capacity
storage_caps_sw_xarxa2 <- numeric()
library(Matrix)
for(j in 1:dim(am_sw_xarxa2)[[1]]){
  storage_caps_sw_xarxa2 <- append(storage_caps_sw_xarxa2, as.integer(2*log2(chooseZ(as.bigz(sum(am_sw_xarxa2[,j]) + nnzero(am_sw_xarxa2[,j]) -1), as.bigz(sum(am_sw_xarxa2[,j]))))))
}
storage_cap_sw_xarxa2 <- mean(storage_caps_sw_xarxa2)#,na.rm=T)

celegansSW_data <- list()
celegansSW_data[["deg_distF_celegansSW"]] <- deg.dist_xarxaF2
celegansSW_data[["deg_distT_celegansSW"]] <- deg.dist_xarxaT2
celegansSW_data[["triad_census_celegansSW"]] <- tirad_sw_xarxa2
celegansSW_data[["hub_score_celegansSW"]] <- hs_sw_xarxa2
celegansSW_data[["modularity_celegansSW"]] <- modularity_sw_xarxa2
celegansSW_data[["authority_score_celegansSW"]] <- as_sw_xarxa2 
celegansSW_data[["communitySize_celegansSW"]] <- communitySize_sw_xarxa2 
celegansSW_data[["SW_ratio_celegansSW"]] <- SM_Ratio_sw_xarxa2 
celegansSW_data[["cliques_celegansSW"]] <- cliques_sw_xarxa2 
celegansSW_data[["nNodes_celegansSW"]] <- nNodes_sw_xarxa2 
celegansSW_data[["rout_eff_celegansSW"]] <- rout_eff_sw_xarxa2 
celegansSW_data[["storage_cap_celegansSW"]] <- storage_cap_sw_xarxa2


save(celegansSW_data, file="celegansSW_data.RData")

load("celegansSW_data.RData")
```


## Barabasi-Albert preferential attachment model for scale-free graphs

```{r}
ba_xarxa3 <-  sample_pa(n=283, power=1, m=11,  directed=F)

deg_xarxa3 <- degree(ba_xarxa3, mode="all")

deg.dist_xarxaF3 <- degree_distribution(ba_xarxa3, cumulative=F, mode="all")

deg.dist_xarxaT3 <- degree_distribution(ba_xarxa3, cumulative=T, mode="all")

tirad_census_ba_xarxa3 = triad_census(ba_xarxa3)

#Hubs
hs_ba_xarxa3 <- hub_score(ba_xarxa3, weights=NA)$vector

#Authorities
as_ba_xarxa3 <- authority_score(ba_xarxa3, weights=NA)$vector

#Small-Worldness ratio: 
SM_Ratio_ba_xarxa3 = transitivity(ba_xarxa3)/mean_distance(ba_xarxa3)

#modularity
library(leiden)
adj_mtx_ba_xarxa3  <- igraph::as_adjacency_matrix(ba_xarxa3)
wtc_ba_xarxa3 <- leiden(adj_mtx_ba_xarxa3)
modularity_ba_xarxa3 <- modularity(ba_xarxa3, wtc_ba_xarxa3)

#comunitats
comunitats_ba_xarxa3 <- cluster_louvain(ba_xarxa3)
communitySize_ba_xarxa3 <- comunitats_ba_xarxa3

#cliques
cliques_ba_xarxa3 <- cliques(ba_xarxa3)

#n nodes
nNodes_ba_xarxa3 <- gsize(ba_xarxa3)

#routing efficiency
am_ba_xarxa3 <- get.adjacency(ba_xarxa3)
distances_ba_xarxa3 <- distances(ba_xarxa3 , mode = "in", weights=1/E(am_ba_xarxa3)$weight)

library(gmp)
rout_effs_ba_xarxa3 <- as.numeric(as.bigz(1/distances_ba_xarxa3)/as.bigz(dim(am_ba_xarxa3)[[1]]*(dim(am_ba_xarxa3)[[1]]-1)))
rout_effs_matrix_ba_xarxa3 <- as.matrix(rout_effs_ba_xarxa3)
rout_effs_matrix_ba_xarxa3 <- rout_effs_matrix_ba_xarxa3[is.finite(rout_effs_matrix_ba_xarxa3)]
rout_eff_ba_xarxa3 <- as.numeric(sum(rout_effs_matrix_ba_xarxa3))

#storage capacity
storage_caps_ba_xarxa3 <- numeric()
library(Matrix)
for(j in 1:dim(am_ba_xarxa3)[[1]]){
  storage_caps_ba_xarxa3 <- append(storage_caps_ba_xarxa3, as.integer(2*log2(chooseZ(as.bigz(sum(am_ba_xarxa3[,j]) + nnzero(am_ba_xarxa3[,j]) -1), as.bigz(sum(am_ba_xarxa3[,j]))))))
}
storage_cap_sw_xarxa2 <- mean(storage_caps_sw_xarxa2)#,na.rm=T)

celegansBA_data <- list()
celegansBA_data[["deg_distF_celegansBA"]] <- deg.dist_xarxaF3
celegansBA_data[["deg_distT_celegansBA"]] <- deg.dist_xarxaT3
celegansBA_data[["triad_census_celegansBA"]] <- tirad_census_ba_xarxa3
celegansBA_data[["hub_score_celegansBA"]] <- hs_ba_xarxa3
celegansBA_data[["modularity_celegansBA"]] <- modularity_ba_xarxa3
celegansBA_data[["authority_score_celegansBA"]] <- as_ba_xarxa3
celegansBA_data[["communitySize_celegansBA"]] <- communitySize_ba_xarxa3 
celegansBA_data[["SW_ratio_celegansBA"]] <- SM_Ratio_ba_xarxa3
celegansBA_data[["cliques_celegansBA"]] <- cliques_ba_xarxa3 
celegansBA_data[["nNodes_celegansBA"]] <- nNodes_ba_xarxa3 
celegansBA_data[["rout_eff_celegansBA"]] <- rout_eff_ba_xarxa3 
celegansBA_data[["storage_cap_celegansBA"]] <- storage_cap_sw_xarxa2 


save(celegansBA_data, file="celegansBA_data.RData")

load("celegansBA_data.RData")
```





```{r}
df_plot1 <- data.frame(deg=rep(0:max(deg),4),
                       freq=c(1-deg.distT,
                              c(1-deg.dist_xarxaT1,rep(1,max(deg)-max(deg_xarxa1))),
                              c(1-deg.dist_xarxaT2,rep(1,max(deg)-max(deg_xarxa2))),
                              c(1-deg.dist_xarxaT3[0:(max(deg)+1)])
                              ),
                       type=c(rep("c.elegans",max(deg)+1),
                              rep("Erdös-Renyi",max(deg)+1),
                              rep("Small-World",max(deg)+1),
                              rep("Barabasi-Alberts",max(deg)+1)
                              )
                       )

library(ggplot2)
ggplot(df_plot1, aes(x=deg,y=freq,color=type)) + geom_point()
```

```{r}
df_plot2 <- data.frame(deg=rep(0:max(deg),4),
                       freq=c(deg.distF,
                              c(deg.dist_xarxaF1,rep(0,max(deg)-max(deg_xarxa1))),
                              c(deg.dist_xarxaF2,rep(0,max(deg)-max(deg_xarxa2))),
                              c(deg.dist_xarxaF3[0:(max(deg)+1)])
                              ),
                       type=c(rep("c.elegans",max(deg)+1),
                              rep("Erdös-Renyi",max(deg)+1),
                              rep("Small-World",max(deg)+1),
                              rep("Barabasi-Alberts",max(deg)+1)
                              )
                       )

library(ggplot2)
ggplot(df_plot2, aes(x=deg,y=freq,color=type)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_log10(limits=c(5,100)) +
  geom_smooth(aes(fill=type)) +
  theme_classic()

```










#----------------------------FLY EM -------------------------------------------------------------------------


```{r}
archiuFly <- read.csv("v1.2_exported-traced-adjacencies-v1.2.csv",sep = ",",header = F,skip = 1)

```

```{r}
#archiuFly[,1] <- as.numeric(as.factor(archiuFly[,1]))
#archiuFly[,2] <- as.numeric(as.factor(archiuFly[,2]))
#archiuFly[,3] <- as.numeric(as.factor(archiuFly[,3]))
#gFly <- graph_from_edgelist(as.matrix(archiuFly[,c(1,2)]), directed = F)
# 
#gFlyS <- simplify( gFly , remove.multiple = T, remove.loops = F, edge.attr.comb=c(weight="sum", type="ignore") )
# 
#save(gFlyS, file="gFlyS.RData")

load("gFlyS.RData")

```

```{r}
#l <- layout_with_fr(gFlyS)
#plot(gFlyS, rescale=F, layout=l*0.4)
```

```{r}
#Degree distribution

#plot(gFlyS, vertex.size=6, vertex.label=NA, layout=layout_in_circle)

degFly <- degree(gFlyS, mode="all")

deg.degFlyF <- degree_distribution(gFlyS, cumulative=F, mode="all")

deg.degFlyT <- degree_distribution(gFlyS, cumulative=T, mode="all")

tirad_census_gFlyS = triad_census(gFlyS)


#Hubs
hs_gFlyS <- hub_score(gFlyS, weights=NA)$vector


#Authorities
as_gFlyS<- authority_score(gFlyS, weights=NA)$vector


#Small-Worldness ratio: 
SM_Ratio_gFlyS = transitivity(gFlyS)/mean_distance(gFlyS)

#modularity
library(leiden)
adj_mtx_gFlyS  <- igraph::as_adjacency_matrix(gFlyS)
wtc_gFlyS <- leiden(adj_mtx_gFlyS)
modularity_gFlyS <- modularity(gFlyS, wtc_gFlyS)

#comunitats
comunitats_gFlyS <- cluster_louvain(gFlyS)
communitySize_gFlyS <- comunitats_gFlyS

#cliques
cliques_gFlyS <- cliques(gFlyS)

FlyEM_data <- list()
FlyEM_data[["deg_distF_FlyEM"]] <- deg.degFlyF
FlyEM_data[["deg_distT_FlyEM"]] <- deg.degFlyT
FlyEM_data[["triad_census_FlyEM"]] <- tirad_census_gFlyS
FlyEM_data[["hub_score_FlyEM"]] <- hs_gFlyS
FlyEM_data[["modularity_FlyEM"]] <- modularity_gFlyS
FlyEM_data[["authority_score_FlyEM"]] <- as_gFlyS 
FlyEM_data[["communitySize_FlyEM"]] <- communitySize_gFlyS 
FlyEM_data[["SW_ratio_FlyEM"]] <- SM_Ratio_gFlyS 
FlyEM_data[["cliques_FlyEM"]] <- cliques_gFlyS 


save(FlyEM_data, file="FlyEM_data.RData")

load("FlyEM_data.RData")




```




```{r}
set.seed(2706)

er_Fly <- sample_gnm(n=length(unique(archiuFly[,1])), m=length(E(gFlyS))) #n= NUmero de nodes (unique(archiuFly[,1])) m=numero de links (length(E(gFlyS)))
#plot(er_Fly, vertex.size=6, vertex.label=NA, layout=layout_in_circle)  


deg_erFly <- degree(er_Fly, mode="all")

deg.dist_erFlyF <- degree_distribution(er_Fly, cumulative=F, mode="all")

deg.dist_erFlyT <- degree_distribution(er_Fly, cumulative=T, mode="all")

tirad_census_er_Fly = triad_census(er_Fly)


#Hubs
hs_er_Fly <- hub_score(er_Fly, weights=NA)$vector


#Authorities
as_er_Fly <- authority_score(er_Fly, weights=NA)$vector


#Small-Worldness ratio: 
SM_Ratio_er_Fly = transitivity(er_Fly)/mean_distance(er_Fly)

#modularity
library(leiden)
adj_mtx_er_Fly  <- igraph::as_adjacency_matrix(er_Fly)
wtc_er_Fly <- leiden(adj_mtx_er_Fly)
modularity_er_Fly <- modularity(er_Fly, wtc_er_Fly)

#comunitats
comunitats_er_Fly <- cluster_louvain(er_Fly)
communitySize_er_Fly <- comunitats_er_Fly

#cliques
cliques_er_Fly <- cliques(er_Fly)

FlyEM_ER_data <- list()
FlyEM_ER_data[["deg_distF_FlyEM_ER"]] <- deg.dist_erFlyF
FlyEM_ER_data[["deg_distT_FlyEM_ER"]] <- deg.dist_erFlyT
FlyEM_ER_data[["triad_census_FlyEM_ER"]] <- tirad_census_er_Fly
FlyEM_ER_data[["hub_score_FlyEM_ER"]] <- hs_er_Fly
FlyEM_ER_data[["modularity_FlyEM_ER"]] <- modularity_er_Fly
FlyEM_ER_data[["authority_score_FlyEM_ER"]] <- as_er_Fly 
FlyEM_ER_data[["communitySize_FlyEM_ER"]] <- communitySize_er_Fly 
FlyEM_ER_data[["SW_ratio_FlyEM_ER"]] <- SM_Ratio_er_Fly
FlyEM_ER_data[["cliques_FlyEM_ER"]] <- cliques_er_Fly 


save(FlyEM_ER_data, file="FlyEM_ER_data.RData")

load("FlyEM_ER_data.RData")
```



```{r}
sw_Fly <- sample_smallworld(dim=1, size=length(unique(archiuFly[,1])), nei=11, p=0.1)
#plot(sw_Fly, vertex.size=6, vertex.label=NA, layout=layout_in_circle)


deg_swFly <- degree(sw_Fly, mode="all")

deg.dist_swFlyF <- degree_distribution(sw_Fly, cumulative=F, mode="all")

deg.dist_swFlyT <- degree_distribution(sw_Fly, cumulative=T, mode="all")

tirad_census_sw_Fly = triad_census(sw_Fly)

#Hubs
hs_sw_Fly <- hub_score(sw_Fly, weights=NA)$vector

#Authorities
as_sw_Fly <- authority_score(sw_Fly, weights=NA)$vector

#Small-Worldness ratio: 
SM_Ratio_sw_Fly = transitivity(sw_Fly)/mean_distance(sw_Fly)

#modularity
library(leiden)
adj_mtx_sw_Fly  <- igraph::as_adjacency_matrix(sw_Fly)
wtc_sw_Fly <- leiden(adj_mtx_sw_Fly)
modularity_sw_Fly <- modularity(sw_Fly, wtc_sw_Fly)

#comunitats
comunitats_sw_Fly <- cluster_louvain(sw_Fly)
communitySize_sw_Fly <- comunitats_sw_Fly

#cliques
cliques_sw_Fly <- cliques(sw_Fly)

FlyEM_SW_data <- list()
FlyEM_SW_data[["deg_distF_FlyEM_SW"]] <- deg.dist_swFlyF
FlyEM_SW_data[["deg_distT_FlyEM_SW"]] <- deg.dist_swFlyT
FlyEM_SW_data[["triad_census_FlyEM_SW"]] <- tirad_census_sw_Fly
FlyEM_SW_data[["hub_score_FlyEM_SW"]] <- hs_sw_Fly
FlyEM_SW_data[["modularity_FlyEM_SW"]] <- modularity_sw_Fly
FlyEM_SW_data[["authority_score_FlyEM_SW"]] <- as_sw_Fly 
FlyEM_SW_data[["communitySize_FlyEM_SW"]] <- communitySize_sw_Fly 
FlyEM_SW_data[["SW_ratio_FlyEM_SW"]] <- SM_Ratio_sw_Fly 
FlyEM_SW_data[["cliques_FlyEM_SW"]] <- cliques_sw_Fly 


save(FlyEM_SW_data, file="FlyEM_SW_data.RData")

load("FlyEM_SW_data.RData")
```


```{r}
ba_fly <-  sample_pa(n=length(unique(archiuFly[,1])), power=1, m=11,  directed=F)
#plot(ba_fly, vertex.size=6, vertex.label=NA, layout=layout_in_circle)


deg_baFly <- degree(ba_fly, mode="all")

deg.dist_baFlyF <- degree_distribution(ba_fly, cumulative=F, mode="all")

deg.dist_baFyT <- degree_distribution(ba_fly, cumulative=T, mode="all")

tirad_census_ba_fly = triad_census(ba_fly)

#Hubs
hs_ba_fly <- hub_score(ba_fly, weights=NA)$vector


#Authorities
as_baFly <- authority_score(ba_fly, weights=NA)$vector


#Small-Worldness ratio: 
SM_Ratio_ba_fly= transitivity(ba_fly)/mean_distance(ba_fly)

#modularity
library(leiden)
adj_mtx_ba_fly  <- igraph::as_adjacency_matrix(ba_fly)
wtc_ba_fly <- leiden(adj_mtx_ba_fly)
modularity_ba_fly <- modularity(ba_fly, wtc_ba_fly)

#comunitats
comunitats_ba_fly <- cluster_louvain(ba_fly)
communitySize_ba_fly <- comunitats_ba_fly

#cliques
cliques_ba_fly <- cliques(ba_fly)

FlyEM_BA_data <- list()
FlyEM_BA_data[["deg_distF_FlyEM_BA"]] <- deg.dist_baFlyF
FlyEM_BA_data[["deg_distT_FlyEM_BA"]] <- deg.dist_baFyT
FlyEM_BA_data[["triad_census_FlyEM_BA"]] <- tirad_census_ba_fly
FlyEM_BA_data[["hub_score_FlyEM_BA"]] <- hs_ba_fly
FlyEM_BA_data[["modularity_FlyEM_BA"]] <- modularity_ba_fly
FlyEM_BA_data[["authority_score_FlyEM_BA"]] <- as_baFly 
FlyEM_BA_data[["communitySize_FlyEM_BA"]] <- communitySize_ba_fly 
FlyEM_BA_data[["SW_ratio_FlyEM_BA"]] <- SM_Ratio_ba_fly 
FlyEM_BA_data[["cliques_FlyEM_BA"]] <- communitySize_ba_fly 


save(FlyEM_BA_data, file="FlyEM_BA_data.RData")

load("FlyEM_BA_data.RData")
```


##----------------------------------------FLY OPTIC--------------------------------------------------------------##



```{r}
archiuFlyOPtic <- read.table("FlyCircuit.csv",sep = ";",row.names=1,header=T)

```

```{r}
gFlyOptic <- graph_from_adjacency_matrix(as.matrix(archiuFlyOPtic))
gFlyOpticS <- simplify(gFlyOptic , remove.multiple = T, remove.loops = F, edge.attr.comb=c(weight="sum", type="ignore") )
```

```{r}
l <- layout_with_fr(gFlyOpticS)
plot(gFlyOpticS, rescale=F, layout=l*0.4)
```


```{r}
#Degree distribution

degFlyOptic <- degree(gFlyOpticS, mode="all")

deg.degFlyOF <- degree_distribution(gFlyOpticS, cumulative=F, mode="all")


deg.degFlyOT <- degree_distribution(gFlyOpticS, cumulative=T, mode="all")


tirad_census_FlyOptic = barplot(triad_census(gFlyOpticS), log="y")


#Hubs
hs_FlyOptic <- hub_score(gFlyOpticS, weights=NA)$vector



#Authorities
as_FlyOptic <- authority_score(gFlyOpticS, weights=NA)$vector

#Small-Worldness ratio: 
SM_Ratio_FlyOptic= transitivity(gFlyOpticS)/mean_distance(gFlyOpticS)

#modularity
library(leiden)
adj_mtx_FlyOptic  <- igraph::as_adjacency_matrix(gFlyOpticS)
wtc_FlyOptic <- leiden(adj_mtx_FlyOptic)
modularity_FlyOptic <- modularity(gFlyOpticS, wtc_FlyOptic)

#comunitats
comunitats_gFlyOpticS <- cluster_louvain(gFlyOpticS)
communitySize_gFlyOpticS <- comunitats_gFlyOpticS

#cliques
cliques_gFlyOpticS <- cliques(gFlyOpticS)

FlyOP_data <- list()
FlyOP_data[["deg_distF_FlyOP"]] <- deg.degFlyOF
FlyOP_data[["deg_distT_FlyOP"]] <- deg.degFlyOT
FlyOP_data[["triad_census_FlyOP"]] <- tirad_census_FlyOptic
FlyOP_data[["hub_score_FlyOP"]] <- hs_FlyOptic
FlyOP_data[["modularity_FlyOP"]] <- modularity_FlyOptic
FlyOP_data[["authority_score_FlyOP"]] <- as_FlyOptic 
FlyOP_data[["communitySize_FlyOP"]] <- communitySize_gFlyOpticS 
FlyOP_data[["cliques_FlyOP"]] <- cliques_gFlyOpticS 

save(FlyOP_data, file="FlyOP_data.RData")

load("FlyOP_data.RData")
```




```{r}
set.seed(2706)

er_FlyO <- sample_gnm(n=length(unique(archiuFlyOPtic[,1])), m=length(E(gFlyOpticS)),directed=F) 


deg_erFlyO <- degree(er_FlyO, mode="all")



deg.dist_erFlyOF <- degree_distribution(er_FlyO, cumulative=F, mode="all")


deg.dist_erFlyOT <- degree_distribution(er_FlyO, cumulative=T, mode="all")


tirad_census_er_FlyO = barplot(triad_census(er_FlyO), log="y")

#Hubs
hs_er_FlyO <- hub_score(er_FlyO, weights=NA)$vector

#Authorities
as_er_FlyO <- authority_score(er_FlyO, weights=NA)$vector

#Small-Worldness ratio: 
SM_Ratio_er_FlyO= transitivity(er_FlyO)/mean_distance(er_FlyO)

#modularity
library(leiden)
adj_mtx_er_FlyO  <- igraph::as_adjacency_matrix(er_FlyO)
wtc_er_FlyO <- leiden(adj_mtx_er_FlyO)
modularity_er_FlyO <- modularity(er_FlyO, wtc_er_FlyO)

#comunitats
comunitats_er_FlyO <- cluster_louvain(er_FlyO)
communitySize_er_FlyO <- comunitats_er_FlyO

#cliques
cliques_er_FlyO <- cliques(er_FlyO)

FlyOP_ER_data <- list()
FlyOP_ER_data[["deg_distF_FlyOP_ER"]] <- deg.dist_erFlyOF
FlyOP_ER_data[["deg_distT_FlyOP_ER"]] <- deg.dist_erFlyOT
FlyOP_ER_data[["triad_census_FlyOP_ER"]] <- tirad_census_er_FlyO
FlyOP_ER_data[["hub_score_FlyOP_ER"]] <- hs_er_FlyO
FlyOP_ER_data[["modularity_FlyOP_ER"]] <- modularity_er_FlyO
FlyOP_ER_data[["authority_score_FlyOP_ER"]] <- as_er_FlyO 
FlyOP_ER_data[["communitySize_FlyOP_ER"]] <- communitySize_er_FlyO 
FlyOP_ER_data[["SW_ratio_FlyOP_ER"]] <- SM_Ratio_er_FlyO 
FlyOP_ER_data[["cliques_FlyOP_ER"]] <- cliques_er_FlyO 


save(FlyOP_ER_data, file="FlyOP_ER_data.RData")

load("FlyOP_ER_data.RData")

```





```{r}
sw_FlyO <- sample_smallworld(dim=1, size=length(unique(archiuFlyOPtic[,1])), nei=11, p=0.1)


deg_swFlyO <- degree(sw_FlyO, mode="all")


deg.dist_swFlyFO <- degree_distribution(sw_FlyO, cumulative=F, mode="all")


deg.dist_swFlyTO <- degree_distribution(sw_FlyO, cumulative=T, mode="all")


tirad_census_sw_FlyO = barplot(triad_census(sw_FlyO), log="y")

#Hubs
hs_sw_FlyO <- hub_score(sw_FlyO, weights=NA)$vector

#Authorities
as_sw_FlyO <- authority_score(sw_FlyO, weights=NA)$vector

#Small-Worldness ratio: 
SM_Ratio_sw_FlyO= transitivity(sw_FlyO)/mean_distance(sw_FlyO)

#modularity
library(leiden)
adj_mtx_sw_FlyO  <- igraph::as_adjacency_matrix(sw_FlyO)
wtc_sw_FlyO <- leiden(adj_mtx_sw_FlyO)
modularity_sw_FlyO <- modularity(sw_FlyO, wtc_sw_FlyO)

#comunitats
comunitats_sw_FlyO <- cluster_louvain(sw_FlyO)
communitySize_sw_FlyO <- comunitats_sw_FlyO

#cliques
cliques_sw_FlyO <- cliques(sw_FlyO)

FlyOP_SW_data <- list()
FlyOP_SW_data[["deg_distF_FlyOP_SW"]] <- deg.dist_swFlyFO
FlyOP_SW_data[["deg_distT_FlyOP_SW"]] <- deg.dist_swFlyTO
FlyOP_SW_data[["triad_census_FlyOP_SW"]] <- tirad_census_sw_FlyO
FlyOP_SW_data[["hub_score_FlyOP_SW"]] <- hs_sw_FlyO
FlyOP_SW_data[["modularity_FlyOP_SW"]] <- modularity_sw_FlyO
FlyOP_SW_data[["authority_score_FlyOP_SW"]] <- as_sw_FlyO
FlyOP_SW_data[["communitySize_FlyOP_SW"]] <- communitySize_sw_FlyO 
FlyOP_SW_data[["SW_ratio_FlyOP_SW"]] <- SM_Ratio_sw_FlyO 
FlyOP_SW_data[["cliques_FlyOP_SW"]] <- cliques_sw_FlyO 


save(FlyOP_SW_data, file="FlyOP_SW_data.RData")

load("FlyOP_SW_data.RData")

```

```{r}
ba_flyO <-  sample_pa(n=length(unique(archiuFlyOPtic[,1])), power=1, m=11,  directed=F)
#plot(ba_fly, vertex.size=6, vertex.label=NA, layout=layout_in_circle)


deg_baFlyO <- degree(ba_flyO, mode="all")


deg.dist_baFlyFO <- degree_distribution(ba_flyO, cumulative=F, mode="all")


deg.dist_baFyTO <- degree_distribution(ba_flyO, cumulative=T, mode="all")


tirad_census_ba_flyO = barplot(triad_census(ba_flyO), log="y")

#Hubs
hs_ba_flyO <- hub_score(ba_flyO, weights=NA)$vector

#Authorities
as_ba_flyO <- authority_score(ba_flyO, weights=NA)$vector

#Small-Worldness ratio: 
SM_Ratio_ba_flyO= transitivity(ba_flyO)/mean_distance(ba_flyO)

#modularity
library(leiden)
adj_mtx_ba_flyO  <- igraph::as_adjacency_matrix(ba_flyO)
wtc_ba_flyO <- leiden(adj_mtx_ba_flyO)
modularity_ba_flyO <- modularity(ba_flyO, wtc_ba_flyO)

#comunitats
comunitats_ba_flyO <- cluster_louvain(ba_flyO)
communitySize_ba_flyO <- comunitats_ba_flyO

#cliques
cliques_ba_flyO <- cliques(ba_flyO)

FlyOP_BA_data <- list()
FlyOP_BA_data[["deg_distF_FlyOP_BA"]] <- deg.dist_baFlyFO
FlyOP_BA_data[["deg_distT_FlyOP_BA"]] <- deg.dist_baFyTO
FlyOP_BA_data[["triad_census_FlyOP_BA"]] <- tirad_census_ba_flyO
FlyOP_BA_data[["hub_score_FlyOP_BA"]] <- hs_ba_flyO
FlyOP_BA_data[["modularity_FlyOP_BA"]] <- modularity_ba_flyO
FlyOP_BA_data[["authority_score_FlyOP_BA"]] <- as_ba_flyO 
FlyOP_BA_data[["communitySize_FlyOP_BA"]] <- communitySize_ba_flyO
FlyOP_BA_data[["SW_ratio_FlyOP_BA"]] <- SM_Ratio_ba_flyO
FlyOP_BA_data[["cliques_FlyOP_BA"]] <- cliques_ba_flyO 


save(FlyOP_BA_data, file="FlyOP_BA_data.RData")

load("FlyOP_BA_data.RData")

```




#----------------------------------------RATOLI-----------------------------------------#


```{r}
archiuRata <- read.csv("affinity_map_nonflip_thres30_20211103.csv",sep = ",")

```

```{r}
archiuDades <- read.csv("mouse_mesoscale_connectivity_matrix.csv",sep = ",",header=FALSE)
archiuNoms <- read.csv("mouse_mesoscale_regionname.csv")

noms <- as.character(archiuNoms$region_name)
  
names(archiuDades) <- noms
rownames(archiuDades) <- noms
```

```{r}

gRatoli <-graph_from_adjacency_matrix(
  as.matrix(archiuDades),
  mode = "directed",
  weighted = TRUE,
  diag = TRUE,
  add.colnames = NULL,
  add.rownames = NA
)
gsRatoli <- simplify( gRatoli , remove.multiple = T, remove.loops = F, edge.attr.comb=c(weight="sum", type="ignore") )

lRatoli <- layout_with_fr(gsRatoli)

plot(gsRatoli, rescale=F, layout=lRatoli*0.4)
```


```{r}
degRatoli <- degree(gsRatoli, mode="all")

deg.distRatoliF <- degree_distribution(gsRatoli, cumulative=F, mode="all")

deg.distRatoliT <- degree_distribution(gsRatoli, cumulative=T, mode="all")



#Triad census
tirad_gsRatoli = triad_census(gsRatoli)

#Hubs
hs_gsRatoli <- hub_score(gsRatoli, weights=NA)$vector

#Authorities
as_gsRatoli <- authority_score(gsRatoli, weights=NA)$vector


#Small-Worldness ratio: 
SM_Ratio_gsRatoli = transitivity(gsRatoli)/mean_distance(gsRatoli)

#modularity
library(leiden)
adj_mtx_gsRatoli  <- igraph::as_adjacency_matrix(gsRatoli)
wtc_gsRatoli <- leiden(adj_mtx_gsRatoli)
modularity_gsRatoli <- modularity(gsRatoli, wtc_gsRatoli)

#comunitats
comunitats_ba_flyO <- cluster_louvain(ba_flyO)
communitySize_ba_flyO <- comunitats_ba_flyO

ratoli_data <- list()
ratoli_data[["deg_distF_ratoli"]] <- deg.distRatoliF
ratoli_data[["deg_distT_ratoli"]] <- deg.distRatoliT
ratoli_data[["triad_census_ratoli"]] <- tirad_gsRatoli
ratoli_data[["hub_score_ratoli"]] <- hs_gsRatoli
ratoli_data[["modularity_ratoli"]] <- modularity_gsRatoli
ratoli_data[["authority_score_ratoli"]] <- as_gsRatoli 
ratoli_data[["SW_ratio_ratoli"]] <- SM_Ratio_gsRatoli 

save(ratoli_data, file="ratoli_data.RData")

load("ratoli_data.RData")

```




```{r}
#routing efficiency
am  <- get.adjacency(graph)
distances_g <- distances(graph , mode = "in", weights=1/E(graph)$weight)

library(gmp)
rout_effs <- as.numeric(as.bigz(1/distances_g)/as.bigz(dim(am)[[1]]*(dim(am)[[1]]-1)))
rout_effs_matrix <- as.matrix(rout_effs)
rout_effs_matrix <- rout_effs_matrix[is.finite(rout_effs_matrix)]
rout_eff <- as.numeric(sum(rout_effs_matrix))

#storage capacity
storage_caps <- numeric()
library(Matrix)
for(j in 1:dim(am)[[1]]){
  storage_caps <- append(storage_caps, as.integer(2*log2(chooseZ(as.bigz(sum(am[,j]) + nnzero(am[,j]) -1), as.bigz(sum(am[,j]))))))
}
storage_cap <- mean(storage_caps)#,na.rm=T)
```

